In [3]:
import pandas as pd

In [4]:

df = pd.read_csv("../data/raw/results.csv")

In [26]:
df.shape

(49472, 9)

In [27]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [28]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [10]:
df["date"] = pd.to_datetime(df["date"])

modern_df = df[df["date"] >= "2010-01-01"]

print(modern_df.shape)

(15884, 9)

In [11]:
def get_result(row):
    if row["home_score"] > row["away_score"]:
        return "H"
    elif row["home_score"] < row["away_score"]:
        return "A"
    return "D"

modern_df["result"] = modern_df.apply(get_result, axis=1)

modern_df["result"].value_counts()

C:\Users\Harish\AppData\Local\Temp\ipykernel_14988\736324082.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modern_df["result"] = modern_df.apply(get_result, axis=1)

result
H    7564
A    4579
D    3741
Name: count, dtype: int64

In [12]:
modern_df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result
33588,2010-01-02,Iran,North Korea,1.0,0.0,Friendly,Doha,Qatar,True,H
33589,2010-01-02,Qatar,Mali,0.0,0.0,Friendly,Doha,Qatar,False,D
33590,2010-01-02,Syria,Zimbabwe,6.0,0.0,Friendly,Kuala Lumpur,Malaysia,True,H
33591,2010-01-02,Yemen,Tajikistan,0.0,1.0,Friendly,Sana'a,Yemen,False,A
33592,2010-01-03,Angola,Gambia,1.0,1.0,Friendly,Vila Real de Santo António,Portugal,True,D

In [13]:
modern_df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result
44748,2021-11-16,Lebanon,United Arab Emirates,0.0,1.0,FIFA World Cup qualification,Sidon,Lebanon,False,A
35025,2011-08-10,Lithuania,Armenia,3.0,0.0,Friendly,Kaunas,Lithuania,False,H
33616,2010-01-13,Cameroon,Gabon,0.0,1.0,African Cup of Nations,Lubango,Angola,True,A
41294,2017-12-28,Saudi Arabia,Oman,0.0,2.0,Gulf Cup,Kuwait City,Kuwait,True,A
43117,2019-10-14,Suriname,Saint Vincent and the Grenadines,0.0,1.0,CONCACAF Nations League,Paramaribo,Suriname,False,A

In [14]:
future_matches = df[
    (df["home_score"].isna()) |
    (df["away_score"].isna())
]

print(future_matches.shape)

future_matches.head(20)

(72, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49400,2026-06-11,Mexico,South Africa,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49401,2026-06-11,South Korea,Czech Republic,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49402,2026-06-12,Canada,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Toronto,Canada,False
49403,2026-06-12,United States,Paraguay,NaN,NaN,FIFA World Cup,Inglewood,United States,False
49404,2026-06-13,Qatar,Switzerland,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49405,2026-06-13,Brazil,Morocco,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49406,2026-06-13,Haiti,Scotland,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49407,2026-06-13,Australia,Turkey,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49408,2026-06-14,Germany,Curaçao,NaN,NaN,FIFA World Cup,Houston,United States,True
49409,2026-06-14,Ivory Coast,Ecuador,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49410,2026-06-14,Netherlands,Japan,NaN,NaN,FIFA World Cup,Arlington,United States,True
49411,2026-06-14,Sweden,Tunisia,NaN,NaN,FIFA World Cup,Guadalupe,Mexico,True
49412,2026-06-15,Belgium,Egypt,NaN,NaN,FIFA World Cup,Seattle,United States,True
49413,2026-06-15,Iran,New Zealand,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49414,2026-06-15,Spain,Cape Verde,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49415,2026-06-15,Saudi Arabia,Uruguay,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49416,2026-06-16,France,Senegal,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49417,2026-06-16,Iraq,Norway,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49418,2026-06-16,Argentina,Algeria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49419,2026-06-16,Austria,Jordan,NaN,NaN,FIFA World Cup,Santa Clara,United States,True

In [15]:
future_matches["date"].min(), future_matches["date"].max()

(Timestamp('2026-06-11 00:00:00'), Timestamp('2026-06-27 00:00:00'))

In [17]:
completed_matches = df[
    df["home_score"].notna() &
    df["away_score"].notna()
].copy()


future_fixtures = df[
    df["home_score"].isna() | 
    df["away_score"].isna()
].copy()

In [18]:
print(completed_matches.shape)
print(future_fixtures.shape)

(49400, 9)
(72, 9)

In [19]:
future_teams = set(future_fixtures["home_team"]).union(
    set(future_fixtures["away_team"])
)

print("Number of teams:", len(future_teams))

for team in sorted(future_teams):
    print(team)

Number of teams: 48
Algeria
Argentina
Australia
Austria
Belgium
Bosnia and Herzegovina
Brazil
Canada
Cape Verde
Colombia
Croatia
Curaçao
Czech Republic
DR Congo
Ecuador
Egypt
England
France
Germany
Ghana
Haiti
Iran
Iraq
Ivory Coast
Japan
Jordan
Mexico
Morocco
Netherlands
New Zealand
Norway
Panama
Paraguay
Portugal
Qatar
Saudi Arabia
Scotland
Senegal
South Africa
South Korea
Spain
Sweden
Switzerland
Tunisia
Turkey
United States
Uruguay
Uzbekistan

In [20]:
future_fixtures["date"].value_counts().sort_index()

date
2026-06-11    2
2026-06-12    2
2026-06-13    4
2026-06-14    4
2026-06-15    4
2026-06-16    4
2026-06-17    4
2026-06-18    4
2026-06-19    4
2026-06-20    4
2026-06-21    4
2026-06-22    4
2026-06-23    4
2026-06-24    6
2026-06-25    6
2026-06-26    6
2026-06-27    6
Name: count, dtype: int64

In [21]:
for team in sorted(future_teams):
    count = len(
        completed_matches[
            (completed_matches["home_team"] == team) |
            (completed_matches["away_team"] == team)
        ]
    )
    print(team, count)

Algeria 616
Argentina 1069
Australia 581
Austria 860
Belgium 853
Bosnia and Herzegovina 283
Brazil 1059
Canada 469
Cape Verde 235
Colombia 638
Croatia 396
Curaçao 385
Czech Republic 360
DR Congo 524
Ecuador 591
Egypt 756
England 1089
France 935
Germany 1031
Ghana 671
Haiti 510
Iran 612
Iraq 655
Ivory Coast 636
Japan 790
Jordan 485
Mexico 1003
Morocco 617
Netherlands 879
New Zealand 416
Norway 872
Panama 539
Paraguay 783
Portugal 694
Qatar 635
Saudi Arabia 741
Scotland 851
Senegal 638
South Africa 480
South Korea 1007
Spain 783
Sweden 1101
Switzerland 884
Tunisia 678
Turkey 642
United States 790
Uruguay 970
Uzbekistan 354